config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def new
end

def create
  @product = Product.new(product_params)

  @product.save
  redirect_to @product
end

def show
  @product = Product.find(params[:id])
end

def index
  @products = Product.all
end

private
  def product_params
    params.require(:product).permit(:name, :weight)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CursoRails1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>Listado de productos</h1>

<% @products.each do |a| %>

<p><%= a.name %>, <%= a.weight %> kg<p>

<% end %>

<%= link_to 'Crear producto', new_product_path %>

app/views/products/new.html.erb
<h1>New Article</h1>
<%= form_for :product, url: products_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @product.weight %>
</p>